### ISSUE TITLE
Is Payum abandoned?

### ISSUE THREAD

**Issue by Tetragramat** [Payum/Payum#854] opened 2020-04-17 18:55 UTC
It's two months since last activity from maintainers.
Last merged PRs felt like they were not reviewed at all.
There are critical bugs in latest versions.
Seeing no activity from maintainers made me reluctant from working on PRs to fix bugs.

Does anybody know what is happening? I wrote email to makasim month ago but got no response.
Are there alternatives to Payum? I know only about Omnipay, but it does not have integration for Symfony.

I use only about 8 custom Payum gateways for local market. 
Using Payum for long time I've found that Payum is far from perfect.
Maybe it's time to develop an alternative?

**Comment by makasim** [comment] 2020-05-21 13:44
I've not used Payum (nor PHP) for a long period of time. Hence it's a low priority for me. 

If someone wants to take over the project, maintain I would gladly give the access and provide initial support.

**Comment by Tetragramat** [comment] 2020-05-22 00:07
I can work on Payum core and Symfony integration, but I have no knowledge about any of Payum payment gateways, because I've never used any of them. So I think I should leave it to someone else.

**Comment by joshbmarshall** [comment] 2020-05-24 13:12
Maybe needs to be a handful of people to maintain the project instead of just one. I have only done bugfixes and PR's for payum, I did manage to create a payment gateway but didn't find it straightforward.

**Comment by Great-Antique** [comment] 2020-05-25 08:31
As I understand [Sylius](https://github.com/Sylius/Sylius) uses Payum as main payment processing library (see their [`composer.json`](https://github.com/Sylius/Sylius/blob/master/composer.json#L46)). It would be great if someone like they take Payum.

**Comment by pixobit** [comment] 2020-06-23 15:01
Too sad, was hoping to use it, but at this point I feel like I'm shooting myself in the foot

**Comment by bennukem** [comment] 2020-09-03 13:25
Hi !

If Payum is still looking for a someone to take the project. I am in.
I am not the best dev of the world but I am still using payum for my project and it will be bad for me if the project die.
My first goal is to keep an high compatibility with symfony  / sytlius.
Second, more documentations about how work the core.
3th ...we will see :dancers: 

ps: I am french, sorry for my poor english :)

**Comment by francesco-laricchia** [comment] 2020-09-29 13:17
Payum website and Github page should warn users and developers that the project is currently unmantained.

**Comment by davidmpaz** [comment] 2020-10-01 11:46
Hello everybody,

Looking at the comments some concerns arose so i did took some actions:

> As I understand Sylius uses Payum as main payment processing library (see their composer.json). It would be great if someone like they take Payum.

I just took the liberty to post in Sylius forum: https://forum.sylius.com/t/payum-library-support/1565, not sure though how much attention will get. They haven't react much to comments made above in their threads.

> Using Payum for long time I've found that Payum is far from perfect. Maybe it's time to develop an alternative?

Are there better alternatives? Does it worth start a new one when this one is proven already?

From my side I am willing also to help since i believe this one is a good piece of software for letting it forgotten and outdated. I did land here since i also want it for a project, so i have direct interest on it.

I am not an expert. Still the main issue for me right now is making it compatible with Symfony 5. I can confirm that by merging a couple of PR I can at least make the whole flow work at least for offline payment. I haven't tried much since i am a PoC stage now and i don't want to diverge too much form mainstream development.

I did merge: https://github.com/Payum/Payum/pull/861 from Payum and this: https://github.com/Payum/PayumBundle/pull/517 from PayumBundle.  

I am not sure how much effort would take to continue the development and fixing bugs so i can not commit to it fully, but at least i can take over integrating any PR and doing fixes that could appear at least until the packages are stabilised again to work with current version of Symfony 5.1

/cc @makasim @Tetragramat @bennukem 

Best regards,
David

**Comment by joshbmarshall** [comment] 2020-10-01 12:36
I've used Omnipay and Payum in a few projects and so far haven't found anything that is superior to Payum in that the developer interface to set up a payment does not depend heavily on the payment gateway. So the code to select a different payment method is really easy.
However to add a payment method that doesn't exist is extremely confusing, with little to no documentation and randomly named functions that if defined cause the gateway to operate in a different way. I built a gateway for Braintree payments https://github.com/joshbmarshall/payum_braintree pretty much by inspecting code in existing gateways for Stripe and PayPal Express.
If Payum were to continue it would be fabulous, but even better if there was documentation on how to properly code a gateway! If an alternative would be started then it has a lot to live up to, but would be really nice if it was written in a way that could be easily understood (usually means less bugs) and have the interface to take payments similar to payum or at least an easy upgrade path.
I don't have much time available as I'm a one-man development business but am more than happy to help out where I can.

**Comment by davidmpaz** [comment] 2020-10-01 12:51
I understand your burden @joshbmarshall 

On the Payum side i am sure that documentation will definitely help. 

Then only left the problems of the "gateways SDKs" they are often changed/deprecated/redesigned and documentation is not always the best. 

IMHO I think that's why libraries like this one are gem and so hard to maintain, you are trying to streamline a chaotic marketplace where every vendor is trying to move away from each other avoiding the streamlining you try to create :D

Btw...Sylius had made a great move in that direction with these:
https://sylius.com/blog/paypal-commerce-platform-becomes-a-global-psp-partner-of-sylius/
https://github.com/Sylius/PayPalPlugin

**Comment by joshbmarshall** [comment] 2020-10-01 13:17
Thanks @davidmpaz - FYI I don't use Sylius so unfortunately their PayPal plugin isn't going to work for me :cry: 
It does indicate to me that perhaps Sylius is looking to move away from Payum.

**Comment by davidmpaz** [comment] 2020-10-01 13:23
No Problems, i am aware of that. 

I am not sure about Sylius moving away from Payum, look at here: https://github.com/Sylius/PayPalPlugin/search?q=Payum they are using it.

Whether the plugin can be used outside of Sylius i have my doubts because of this line: https://github.com/Sylius/PayPalPlugin/blob/master/composer.json#L10

**Comment by Tetragramat** [comment] 2020-10-01 13:35
Even after half year nobody took over the project. Only me and @bennukem is willing to be maintainer. It would be great if someone else joined too and so we took over the project as group. I can give it only several hours per week. I have experience maintaining only [several tiny projects](https://github.com/czechphp).

**Comment by makasim** [comment] 2020-10-01 13:42
I'd be happy to see the project continue to live and evolve. So, I am open to granting access to some people who willing to maintain the project. 

Though I am not sure that giving access right away is a good idea. 
There are many people who rely on the library and might be affected if some bad actions are made.

That's the plan I've come up with (feel free to suggest any changes):

* Somehow let me know that you want maintain the project, for example, comment in this issue.
* Than you can do PRs or review existing one. If you think that PR is good to go - tag me. 
* We could work this way for some time. Once the trust is established I'll grant access to the repository so you could go on on your own.

Thoughts?

**Comment by joshbmarshall** [comment] 2020-10-01 13:52
Great to see this thread has got some attention. @makasim I think your proposal is fair and the safest option. @Tetragramat I also think a team is a better option. I'm willing to help out too. @makasim I have a PR that would be great to go live #839 just don't know how many people would still be using older stripe versions. Will tag you there

**Comment by bennukem** [comment] 2020-10-01 15:45
I would like maintain the project with @Tetragramat, it s sound good. If someone want to be a 3th part it can be helpfull to do more easy roadmap choices for future.
@makasim for me, no problem with limited roles on the project.

**Comment by dukusz** [comment] 2020-10-06 07:31
Hi everyone! Just to make it clear for everyone - the PayPal plugin still relies on Payum as every other payment method integration in the Sylius Ecosystem. We are in the situation that we cannot ditch Payum anyhow and at the same time do not have resources to maintain it. Perhaps next year, when we have more devs on board, we will be able to contribute more.

Anyway, we are glad to see there are new volunteers now willing to push this project forward. :) Fingers crossed!

**Comment by davidmpaz** [comment] 2020-10-06 15:27
Hi @dukusz, thank you for clarifying. 

Still, i would consider dedicate resources for helping out. If the situation is as you did state: 
> We are in the situation that we cannot ditch Payum anyhow...

The risk of relying in an outdated and unsupported library is way too high for the Sylius Ecosystem in my opinion. I know i would not risk myself ;-)

**Comment by acornforth** [comment] 2021-02-26 10:46
Hi all, I realise I'm a little late to the party with this, but for what it's worth, I have been developing on Sylius platform almost exclusively for the last 2 years, and have built a Payment Gateway Plugin for Sylius/Payum which is in production use on 2 sites currently and soon to be a 3rd.
I am now getting quite familiar with Payum itself, and the process of adding Gateways (though it's not exactly the same doing it in Sylius vs Payum alone).

In the interest of supporting this project would be very happy to come on board as a maintainer/contributor.

**Comment by makasim** [comment] 2021-03-21 19:05
@pierredup you've recently done a lot of work on the project. 

Are you willing to maintain the project? I'd be happy to give you the access.

**Comment by pierredup** [comment] 2021-03-22 06:29
Hi @makasim. I would be happy to take over the maintenance of the project.

**Comment by makasim** [comment] 2021-03-22 09:59
This is great! I've granted access to all Payum repos @pierredup. 

Closing the issues since we have new maintainer. 

There is a lot of work so any help from the community would be highly appreciated.

**Closed by makasim** 2021-03-22 09:59 UTC

**Comment by dpfaffenbauer** [comment] 2021-03-22 10:32
🎉  Glad to have a new maintainer. Welcome aboard @pierredup and all the best for the future of payum

**Comment by pierredup** [comment] 2021-03-22 10:51
Thank you for the access @makasim. Can you please grant me write access to Payum/Payum and Payum/PayumBundle as well? I can't close issues or add labels to those repos (but can do on the other repos)

**Comment by makasim** [comment] 2021-03-22 11:01
should be fine now.

**Comment by stumbik** [comment] 2021-03-22 16:44
Hi, we are using Payum in @ftshp and we also would like to contribute to its development.
